### ISSUE TITLE
Feedback, 4 Jan 2023

### ISSUE THREAD

**Issue by hendroucc** [Fatinefadli/asc-assessment-fadlifatine-main#1]
### Holdings Contract

`purchase`:
- Add the following check (Payment amount should include fees to cover the inner transaction).
```
Assert(Gtxn[0].amount() == App.globalGet(Bytes("current_price")) * amountOftesla + Int(1000))
```

(https://github.com/Fatinefadli/asc-assessment-fadlifatine-main/blob/main/assets/holdings_approval.py#L62)

**Comment by Fatinefadli** [comment]
https://github.com/Fatinefadli/asc-assessment-fadlifatine-main

**Comment by Fatinefadli** [comment]
Bonjour j’espère que vous allez bien j’ai rien reçue dès le 4 janvier.
C’est correcte ou bien il existe d’autre chose à régler.
Cordialement

**Comment by hendroucc** [comment]
Everything is good. Well done
